/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gmkeysSol from "./gmkeys.sol";
export type { gmkeysSol };
import type * as randomnessSol from "./randomness.sol";
export type { randomnessSol };
