/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethServiceSol from "./eth.service.sol";
export type { ethServiceSol };
import type * as mintServiceSol from "./mint.service.sol";
export type { mintServiceSol };
