/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Randomness {
  export type NftStructStruct = {
    status: BigNumberish;
    randomNumber: BigNumberish;
    timestamp: BigNumberish;
  };

  export type NftStructStructOutput = [number, BigNumber, BigNumber] & {
    status: number;
    randomNumber: BigNumber;
    timestamp: BigNumber;
  };
}

export interface RandomnessInterface extends utils.Interface {
  contractName: "Randomness";
  functions: {
    "getFee()": FunctionFragment;
    "getKeyHash()": FunctionFragment;
    "getNftCount()": FunctionFragment;
    "getOneNft(bytes32)": FunctionFragment;
    "isMintingStart()": FunctionFragment;
    "mintPhase()": FunctionFragment;
    "nftKeys(bytes32)": FunctionFragment;
    "nfts(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "rawFulfillRandomness(bytes32,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "startMintPhase()": FunctionFragment;
    "stopMintPhase()": FunctionFragment;
    "totalKeys()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uniqKeys(bytes32)": FunctionFragment;
    "unlockNft(bytes32)": FunctionFragment;
    "updateTotalKeys(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNftCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOneNft",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMintingStart",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mintPhase", values?: undefined): string;
  encodeFunctionData(functionFragment: "nftKeys", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "nfts", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomness",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startMintPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stopMintPhase",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalKeys", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "uniqKeys", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "unlockNft",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTotalKeys",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getKeyHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNftCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOneNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMintingStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintPhase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nftKeys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nfts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startMintPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopMintPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalKeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uniqKeys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlockNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalKeys",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Randomness extends BaseContract {
  contractName: "Randomness";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RandomnessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getKeyHash(overrides?: CallOverrides): Promise<[string]>;

    getNftCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOneNft(
      _identifier: BytesLike,
      overrides?: CallOverrides
    ): Promise<[Randomness.NftStructStructOutput]>;

    isMintingStart(overrides?: CallOverrides): Promise<[boolean]>;

    mintPhase(overrides?: CallOverrides): Promise<[number]>;

    nftKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    nfts(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber] & {
        status: number;
        randomNumber: BigNumber;
        timestamp: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startMintPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopMintPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalKeys(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniqKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    unlockNft(
      _identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateTotalKeys(
      _totalKey: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getFee(overrides?: CallOverrides): Promise<BigNumber>;

  getKeyHash(overrides?: CallOverrides): Promise<string>;

  getNftCount(overrides?: CallOverrides): Promise<BigNumber>;

  getOneNft(
    _identifier: BytesLike,
    overrides?: CallOverrides
  ): Promise<Randomness.NftStructStructOutput>;

  isMintingStart(overrides?: CallOverrides): Promise<boolean>;

  mintPhase(overrides?: CallOverrides): Promise<number>;

  nftKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  nfts(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber] & {
      status: number;
      randomNumber: BigNumber;
      timestamp: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  rawFulfillRandomness(
    requestId: BytesLike,
    randomness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startMintPhase(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopMintPhase(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalKeys(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniqKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  unlockNft(
    _identifier: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateTotalKeys(
    _totalKey: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    getKeyHash(overrides?: CallOverrides): Promise<string>;

    getNftCount(overrides?: CallOverrides): Promise<BigNumber>;

    getOneNft(
      _identifier: BytesLike,
      overrides?: CallOverrides
    ): Promise<Randomness.NftStructStructOutput>;

    isMintingStart(overrides?: CallOverrides): Promise<boolean>;

    mintPhase(overrides?: CallOverrides): Promise<number>;

    nftKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    nfts(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber] & {
        status: number;
        randomNumber: BigNumber;
        timestamp: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    startMintPhase(overrides?: CallOverrides): Promise<void>;

    stopMintPhase(overrides?: CallOverrides): Promise<void>;

    totalKeys(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uniqKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    unlockNft(_identifier: BytesLike, overrides?: CallOverrides): Promise<void>;

    updateTotalKeys(
      _totalKey: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    getKeyHash(overrides?: CallOverrides): Promise<BigNumber>;

    getNftCount(overrides?: CallOverrides): Promise<BigNumber>;

    getOneNft(
      _identifier: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMintingStart(overrides?: CallOverrides): Promise<BigNumber>;

    mintPhase(overrides?: CallOverrides): Promise<BigNumber>;

    nftKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    nfts(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startMintPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopMintPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalKeys(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniqKeys(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    unlockNft(
      _identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateTotalKeys(
      _totalKey: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getKeyHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNftCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOneNft(
      _identifier: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMintingStart(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintPhase(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftKeys(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nfts(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startMintPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopMintPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalKeys(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniqKeys(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unlockNft(
      _identifier: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateTotalKeys(
      _totalKey: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
